default: &default
  adapter: postgresql
  username: <%= ENV['RAILS_PGSQL_USER'] %>
  password: <%= ENV['RAILS_PGSQL_PASSWORD'] %>
  host: <%= ENV['RAILS_PGSQL_HOST'] %>
  local_infile: true

development:
  <<: *default
  database: hometime_dev

test: &test
  <<: *default 
  database: hometime_test
